CREATE DATABASE IF NOT EXISTS practice;

USE practice;

# 创建博客用户表
CREATE TABLE IF NOT EXISTS user (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '这是表的主键',
  username VARCHAR(25) NOT NULL COMMENT '用户名',
  password VARCHAR(32) NOT NULL COMMENT '密码，后续会升级为md5加密',
  age TINYINT NOT NULL COMMENT '用户年龄'
);
# ALTER TABLE user ADD age TINYINT NOT NULL COMMENT '用户年龄'